#!/usr/bin/env node
/*
 * Builds the single distributable file: dist/yes-statement.html
 *
 *   node build.mjs [--out path/to/file.html] [--modules overview,explorer] [--no-minify]
 *
 * - Inlines every src/css/*.css and src/js/*.js (sorted by filename) into
 *   src/index.html. No external CSS, fonts, scripts or media are referenced.
 * - Inlines the brand artwork (src/brand/*.png, named by path in 00-config.js)
 *   and IBM Plex Sans (woff2, from @fontsource/ibm-plex-sans) as data: URIs.
 * - Release gate: evaluates the data + reconciliation code and refuses to build
 *   if the statement does not reconcile (PRD 5.2, 6).
 * - Runs the offline PDF writer (src/js/07-pdf.js) on a fixed sample and
 *   requires byte-identical output from the minified code.
 * - Generates a static, bilingual <noscript> summary from the same data object
 *   and the shipped EN/ES strings.
 * - Strips comments and indentation from the inlined CSS and JS (never inside
 *   strings, template literals or regular expressions; line breaks are kept, so
 *   automatic semicolon insertion is unchanged). --no-minify keeps the sources
 *   verbatim for debugging.
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, 'src');
const args = process.argv.slice(2);
const outArg = args.indexOf('--out');
const OUT = resolve(outArg !== -1 ? args[outArg + 1] : join(ROOT, 'dist', 'yes-statement.html'));
const MINIFY = !args.includes('--no-minify');

// --modules overview,explorer → build only the foundation plus the named feature
// modules (lets several modules be developed and tested in isolation).
const modArg = args.indexOf('--modules');
const ONLY = modArg !== -1 ? args[modArg + 1].split(',').filter(Boolean) : null;
const isFoundation = (f) => /^(0\d|9\d)-/.test(f);
const list = (dir, ext) =>
  readdirSync(join(SRC, dir))
    .filter((f) => f.endsWith(ext))
    .filter((f) => !ONLY || isFoundation(f) || ONLY.some((m) => f.includes(m)))
    .sort()
    .map((f) => ({ name: `${dir}/${f}`, body: readFileSync(join(SRC, dir, f), 'utf8') }));

const cssFiles = list('css', '.css');
const jsFiles = list('js', '.js');
const fail = (msg) => {
  console.error(msg);
  process.exit(1);
};

/* ---------------------------------------------------------- Brand artwork */
// Approved YES artwork lives in src/brand/ as PNG files. src/js/00-config.js
// names each one by path ('brand/yes-logo-black.png'); the build swaps every
// such string for the image as a data: URI, so the file still fetches nothing.
// Run unbuilt, ui.logoHtml() ignores a path and shows the text placeholder.
const BRAND = join(SRC, 'brand');
const brandUri = (file) => {
  const path = join(BRAND, file);
  if (!existsSync(path)) fail(`✖ 00-config.js names brand/${file}, which is missing.`);
  const type = { png: 'image/png', svg: 'image/svg+xml', webp: 'image/webp' }[file.split('.').pop().toLowerCase()];
  if (!type) fail(`✖ brand/${file}: unsupported image type.`);
  return `data:${type};base64,` + readFileSync(path).toString('base64');
};
{
  const cfg = jsFiles.find((f) => f.name === 'js/00-config.js');
  if (cfg) {
    cfg.body = cfg.body.replace(/'brand\/([\w.-]+)'/g, (m, file) => `'${brandUri(file)}'`);
    if (/['"]brand\//.test(cfg.body)) fail('✖ 00-config.js: a brand/ path was not inlined (use single quotes).');
  }
}

/* ------------------------------------------------------------------ Fonts */
// IBM Plex Sans (SIL Open Font License 1.1, © IBM Corp.), latin subset, from
// @fontsource/ibm-plex-sans: 400, 500, 600 and 700, inlined as woff2 data: URIs
// in a generated stylesheet that comes before every other one.
const FONT_DIR = join(ROOT, 'node_modules', '@fontsource', 'ibm-plex-sans', 'files');
const FONT_WEIGHTS = [400, 500, 600, 700];
const FONT_RANGE = 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD';
{
  const faces = FONT_WEIGHTS.map((w) => {
    const file = join(FONT_DIR, `ibm-plex-sans-latin-${w}-normal.woff2`);
    if (!existsSync(file)) fail(`✖ Font missing: ${file}. Run npm install (devDependency @fontsource/ibm-plex-sans).`);
    const uri = 'data:font/woff2;base64,' + readFileSync(file).toString('base64');
    return `@font-face {\n  font-family: 'IBM Plex Sans';\n  font-style: normal;\n  font-weight: ${w};\n  font-display: swap;\n  src: url('${uri}') format('woff2');\n  unicode-range: ${FONT_RANGE};\n}`;
  });
  cssFiles.unshift({
    name: 'css/00-fonts.css',
    body: '/* Generated by build.mjs: IBM Plex Sans (SIL Open Font License 1.1, Copyright IBM Corp.), latin subset, from @fontsource/ibm-plex-sans. */\n' + faces.join('\n') + '\n'
  });
}

/* ------------------------------------------------------ Recorded voiceover */
// src/media/voiceover.json (written by scripts/voiceover.mjs) lists one MP3 per
// language. Each is packaged as a data: URI in YES.config.slots.VIDEO_VOICEOVER
// with the fingerprint of the script it was recorded for, so the file still
// fetches nothing and the player can refuse a recording that no longer matches
// the statement (10-overview.js scriptHash()). A value already set in
// 00-config.js wins over the packaged one.
const MEDIA = join(SRC, 'media');
const voiceManifest = existsSync(join(MEDIA, 'voiceover.json')) ? JSON.parse(readFileSync(join(MEDIA, 'voiceover.json'), 'utf8')) : null;
if (voiceManifest) {
  const entries = Object.entries(voiceManifest.languages || {}).map(([lang, m]) => {
    const file = join(MEDIA, m.file);
    if (!existsSync(file)) {
      console.error(`✖ Voiceover manifest names ${m.file}, which is missing.`);
      process.exit(1);
    }
    const value = { src: 'data:audio/mpeg;base64,' + readFileSync(file).toString('base64'), scriptHash: m.scriptHash, voice: voiceManifest.voice && voiceManifest.voice.name, duration: m.duration };
    return `  if (v[${JSON.stringify(lang)}] == null) v[${JSON.stringify(lang)}] = ${JSON.stringify(value)};`;
  });
  const body = [
    '/* Generated by build.mjs from src/media/voiceover.json (scripts/voiceover.mjs): packaged voiceover recordings. */',
    '(function (root) {',
    "  'use strict';",
    // Tests of the device-voice path set window.YES_SKIP_PACKAGED_MEDIA before the bundle runs.
    '  if (root.YES_SKIP_PACKAGED_MEDIA) return;',
    '  var s = root.YES.config.slots;',
    '  var v = s.VIDEO_VOICEOVER || (s.VIDEO_VOICEOVER = {});',
    ...entries,
    "})(typeof window !== 'undefined' ? window : globalThis);",
    ''
  ].join('\n');
  const at = jsFiles.findIndex((f) => f.name === 'js/00-config.js');
  jsFiles.splice(at + 1, 0, { name: 'js/00-media.js', body });
}
/* --------------------------------------------------------- Foundation sandbox */
// Config, data, arithmetic and localisation have no DOM dependency, so the build
// runs the very code the page runs.
function foundation(files) {
  const sandbox = { console, Intl, Date, Math, JSON };
  sandbox.globalThis = sandbox;
  vm.createContext(sandbox);
  for (const f of files.filter((f) => /^js\/(0[0-3]|07)-/.test(f.name))) vm.runInContext(f.body, sandbox, { filename: f.name });
  return sandbox.YES;
}
const YES = foundation(jsFiles);

/* The PDF writer (07-pdf.js) has no DOM dependency either: the build draws a
   small fixed document with it, so a minified writer must produce the very
   same bytes. */
function pdfSample(Y) {
  if (!Y.pdf) return null;
  const doc = Y.pdf.create({ title: 'Build check — año', lang: 'es-ES', date: '2026-01-01T00:00:00Z' });
  doc.watermark('DATOS ILUSTRATIVOS DE DEMOSTRACIÓN');
  doc.text('Señal ' + String.fromCharCode(0x2212) + '2,50 ≈ → ✓ (paréntesis) \\ € “x”', 54, 54, { font: 'bold' });
  doc.text('1.147,50' + String.fromCharCode(0xa0) + 'USBC', 558, 80, { align: 'right' });
  doc.paragraph('Una línea larga que se parte en varias líneas dentro de la columna.', 54, 100, { width: 120 });
  return Array.from(doc.save()).join(',');
}
const PDF_SAMPLE = pdfSample(YES);
if (PDF_SAMPLE !== null && !PDF_SAMPLE.startsWith([...'%PDF-1.4'].map((c) => c.charCodeAt(0)).join(','))) fail('✖ PDF writer: the sample document is not a PDF 1.4 file.');

// ---------------------------------------------------------------- Release gate
const result = YES.calc.reconcile(YES.data);
if (!result.ok) {
  console.error('\n✖ Release gate: statement does not reconcile. Build refused.\n');
  for (const c of result.checks.filter((c) => !c.ok)) console.error(`  - ${c.id}: ${JSON.stringify(c.detail)}`);
  process.exit(1);
}

/* ------------------------------------------------------------------ Minifier */
/*
 * Conservative: removes comments, leading indentation, trailing spaces and blank
 * lines. Everything inside strings, template literals and regular-expression
 * literals is copied verbatim. File markers ("/* ---- js/… ---- *\/") are kept.
 */
const KEEP_COMMENT = /^\/\* ---- [\w./-]+ ---- \*\/$/;
const REGEX_AFTER_WORD = new Set(['return', 'typeof', 'case', 'do', 'else', 'in', 'instanceof', 'new', 'delete', 'void', 'throw', 'yield', 'await', 'of']);

function minifyJs(src, tokens) {
  // Output as a list of chunks: re-scanning one growing string at every line
  // break is quadratic, which a packaged recording (a 1 MB+ string) makes slow.
  const parts = [];
  const lastChar = () => {
    for (let k = parts.length - 1; k >= 0; k--) if (parts[k]) return parts[k][parts[k].length - 1];
    return '';
  };
  let i = 0;
  const n = src.length;
  let lastSig = ''; // last significant character emitted outside comments
  let lastWord = '';
  const braces = []; // template-literal nesting: 'tpl' marks a ${ … } expression
  const isIdent = (c) => /[\w$]/.test(c);
  const emit = (s, token = true) => {
    parts.push(s);
    if (tokens && token && !/^\s+$/.test(s)) tokens.push(s);
  };
  const newline = () => {
    // Drop trailing spaces/tabs (possibly spread over several chunks), then end the line once.
    while (parts.length) {
      const k = parts.length - 1;
      const trimmed = parts[k].replace(/[ \t]+$/, '');
      if (trimmed) {
        parts[k] = trimmed;
        break;
      }
      parts.pop();
    }
    if (lastChar() !== '\n') parts.push('\n');
    while (i < n && (src[i] === ' ' || src[i] === '\t')) i++;
  };
  const regexAllowed = () => {
    if (!lastSig) return true;
    if (isIdent(lastSig)) return REGEX_AFTER_WORD.has(lastWord);
    return !/[)\]]/.test(lastSig) && lastSig !== '`' && lastSig !== '"' && lastSig !== "'";
  };
  const readString = (q) => {
    let s = q;
    i++;
    while (i < n) {
      const c = src[i];
      s += c;
      i++;
      if (c === '\\') {
        s += src[i];
        i++;
      } else if (c === q) break;
      else if (c === '\n') throw new Error('unterminated string near ' + JSON.stringify(src.slice(i - 40, i)));
    }
    return s;
  };
  const readTemplateChunk = () => {
    // From just after ` or } (of ${…}) to the closing ` or the next ${.
    let s = '';
    while (i < n) {
      const c = src[i];
      if (c === '\\') {
        s += c + src[i + 1];
        i += 2;
        continue;
      }
      if (c === '`') {
        s += c;
        i++;
        return { s, open: false };
      }
      if (c === '$' && src[i + 1] === '{') {
        s += '${';
        i += 2;
        return { s, open: true };
      }
      s += c;
      i++;
    }
    throw new Error('unterminated template literal');
  };
  const readRegex = () => {
    let s = '/';
    i++;
    let inClass = false;
    while (i < n) {
      const c = src[i];
      s += c;
      i++;
      if (c === '\\') {
        s += src[i];
        i++;
      } else if (c === '[') inClass = true;
      else if (c === ']') inClass = false;
      else if (c === '/' && !inClass) break;
      else if (c === '\n') throw new Error('unterminated regex near ' + JSON.stringify(src.slice(i - 40, i)));
    }
    while (i < n && /[a-z]/i.test(src[i])) s += src[i++];
    return s;
  };

  while (i < n) {
    const c = src[i];
    const d = src[i + 1];
    if (c === '\n') {
      i++;
      newline();
      continue;
    }
    if (c === '/' && d === '/') {
      while (i < n && src[i] !== '\n') i++;
      continue;
    }
    if (c === '/' && d === '*') {
      const end = src.indexOf('*/', i + 2);
      if (end === -1) throw new Error('unterminated comment');
      const body = src.slice(i, end + 2);
      i = end + 2;
      if (KEEP_COMMENT.test(body)) emit(body, false);
      else if (body.includes('\n')) newline();
      else if (isIdent(lastChar()) && isIdent(src[i] || '')) emit(' ');
      continue;
    }
    if (c === '"' || c === "'") {
      emit(readString(c));
      lastSig = c;
      continue;
    }
    if (c === '`') {
      i++;
      const chunk = readTemplateChunk();
      emit('`' + chunk.s);
      if (chunk.open) braces.push('tpl');
      else lastSig = '`';
      if (chunk.open) lastSig = '{';
      continue;
    }
    if (c === '{') {
      braces.push('{');
      emit(c);
      lastSig = c;
      i++;
      continue;
    }
    if (c === '}') {
      const top = braces.pop();
      i++;
      if (top === 'tpl') {
        const chunk = readTemplateChunk();
        emit('}' + chunk.s);
        if (chunk.open) {
          braces.push('tpl');
          lastSig = '{';
        } else lastSig = '`';
      } else {
        emit(c);
        lastSig = c;
      }
      continue;
    }
    if (c === '/' && regexAllowed()) {
      emit(readRegex());
      lastSig = '/';
      lastWord = '';
      continue;
    }
    if (isIdent(c)) {
      let w = '';
      while (i < n && isIdent(src[i])) w += src[i++];
      emit(w);
      lastSig = w[w.length - 1];
      lastWord = w;
      continue;
    }
    emit(c);
    i++;
    if (c !== ' ' && c !== '\t' && c !== '\r') {
      lastSig = c;
      lastWord = '';
    }
  }
  return parts
    .join('')
    .replace(/[ \t]+$/gm, '')
    .replace(/^\n+/, '');
}

function minifyCss(src) {
  let out = '';
  let i = 0;
  const n = src.length;
  while (i < n) {
    const c = src[i];
    if (c === '/' && src[i + 1] === '*') {
      const end = src.indexOf('*/', i + 2);
      const body = src.slice(i, end + 2);
      i = end + 2;
      if (KEEP_COMMENT.test(body)) out += body;
      continue;
    }
    if (c === '"' || c === "'") {
      let s = c;
      i++;
      while (i < n) {
        const ch = src[i++];
        s += ch;
        if (ch === '\\') s += src[i++];
        else if (ch === c) break;
      }
      out += s;
      continue;
    }
    if (c === '\n') {
      out = out.replace(/[ \t]+$/, '');
      if (!out.endsWith('\n')) out += '\n';
      i++;
      while (i < n && (src[i] === ' ' || src[i] === '\t')) i++;
      continue;
    }
    out += c;
    i++;
  }
  return out.replace(/^\n+/, '');
}

/* Token stream of a JS source (strings, template chunks, regular expressions,
   words and punctuation; no whitespace or comments). Minifying must not change
   it by a single token. */
function jsTokens(src) {
  const tokens = [];
  minifyJs(src, tokens);
  return tokens;
}

// -------------------------------------------------------------- Syntax check
const jsSource = jsFiles.map((f) => `/* ---- ${f.name} ---- */\n${f.body}`).join('\n');
try {
  new vm.Script(jsSource, { filename: 'bundle.js' });
} catch (e) {
  fail('✖ JavaScript syntax error: ' + e.message);
}
if (/<\/script/i.test(jsSource)) fail('✖ A JS source contains "</script" — escape it (e.g. "<\\/script").');
const cssSource = cssFiles.map((f) => `/* ---- ${f.name} ---- */\n${f.body}`).join('\n');
if (/@import|url\((?!\s*['"]?data:)/i.test(cssSource)) fail('✖ CSS references an external resource (@import or url()). Inline it as a data: URI.');

let js = jsSource;
let css = cssSource;
if (MINIFY) {
  try {
    js = minifyJs(jsSource);
    css = minifyCss(cssSource);
  } catch (e) {
    fail('✖ Minifier: ' + e.message + ' (build with --no-minify to inspect)');
  }
  try {
    new vm.Script(js, { filename: 'bundle.min.js' });
  } catch (e) {
    fail('✖ Minified JavaScript does not parse: ' + e.message + ' (build with --no-minify to inspect)');
  }
  if (minifyJs(js) !== js || minifyCss(css) !== css) fail('✖ Minifier is not stable: re-minifying changed the output.');
  const before = jsTokens(jsSource);
  const after = jsTokens(js);
  const at = before.findIndex((tok, k) => tok !== after[k]);
  if (at !== -1 || before.length !== after.length) fail('✖ Minifier changed the JavaScript token stream near ' + JSON.stringify(before.slice(Math.max(0, at - 3), at + 3)));
  // The foundation must behave identically: same data, same strings, same gate.
  const min = foundation(js.split(/(?=\/\* ---- js\/)/).map((body) => ({ name: body.match(/^\/\* ---- (js\/[^ ]+) ----/)[1], body })));
  const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
  if (!same(min.data, YES.data) || !same(min.config, YES.config) || !same(min.i18n.dict, YES.i18n.dict) || !same(min.calc.reconcile(min.data), result)) {
    fail('✖ Minified foundation differs from the source (data, config, strings or release gate).');
  }
  if (pdfSample(min) !== PDF_SAMPLE) fail('✖ Minified PDF writer produces different bytes from the source.');
}

// ------------------------------------------------------------ Noscript summary
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);
const s = YES.data.statement;
const { t, fmt, L } = { t: YES.t, fmt: YES.fmt, L: YES.L };
const tzShort = (iso) => fmt.tz(iso).split(' (')[0];
function summary(lang, level) {
  YES.i18n.lang = lang;
  const h = (k) => `h${level + k}`;
  const amt = (m, sign) => fmt.amount(m, { sign: sign ? 'always' : 'auto' });
  const rows = YES.calc
    .posted(YES.data)
    .map(
      (x) =>
        `<tr><td>${esc(fmt.date(x.postedAt, 'medium'))}</td><td>${esc(t('type.' + x.type))}</td><td>${esc(L(x.description))}</td><td>${esc(L(x.counterparty))}</td><td style="text-align:right">${esc(amt(x.amount, true))}</td><td style="text-align:right">${esc(amt(x.balanceAfter))}</td></tr>`
    )
    .join('');
  const pending = YES.calc
    .notInBalance(YES.data)
    .map((x) => `<li>${esc(t('noscript.pendingItem', { date: fmt.date(x.initiatedAt, 'medium'), description: L(x.description), amount: amt(x.amount, true), status: t('status.' + x.status) }))}</li>`)
    .join('');
  const cats = YES.calc
    .categories(YES.data)
    .map((c) => `<li>${esc(t('cat.' + c.id))}: ${esc(amt(c.total, true))}</li>`)
    .join('');
  return `<section lang="${lang}">
<p><strong>${esc(t('demo.watermark'))}.</strong> ${esc(t('app.noscript'))}</p>
<${h(0)}>${esc(t('noscript.heading', { period: fmt.range(s.periodStart, s.periodEnd) }))}</${h(0)}>
<p>${esc(t('noscript.ids', { id: s.id, version: s.version, account: s.account.maskedId }))}</p>
<p>${esc(t('noscript.times', { asOf: fmt.date(s.asOf, 'datetime') + ' ' + tzShort(s.asOf), generated: fmt.date(s.generatedAt, 'datetime') + ' ' + tzShort(s.generatedAt) }))}</p>
<p>${esc(t('noscript.basis', { tz: fmt.tz(s.asOf) }))}</p>
<p>${esc(t('noscript.balances', { opening: amt(s.opening), closing: amt(s.closing) }))}</p>
<ul>${cats}</ul>
<table><caption>${esc(t('noscript.posted'))}</caption><thead><tr><th>${esc(t('term.postedDate'))}</th><th>${esc(t('noscript.type'))}</th><th>${esc(t('noscript.description'))}</th><th>${esc(t('noscript.counterparty'))}</th><th>${esc(t('noscript.amount'))}</th><th>${esc(t('noscript.balanceAfter'))}</th></tr></thead><tbody>${rows}</tbody></table>
${pending ? `<${h(1)}>${esc(t('noscript.notInBalance'))}</${h(1)}><ul>${pending}</ul>` : ''}
</section>`;
}
const langs = [s.language || YES.config.defaultLanguage, ...YES.config.languages.filter((l) => l !== (s.language || YES.config.defaultLanguage))];
const noscript = `<div class="noscript-summary">
${langs.map((l, k) => summary(l, k === 0 ? 1 : 2)).join('\n<hr>\n')}
</div>`;
YES.i18n.lang = YES.config.defaultLanguage;

// ------------------------------------------------------------------- Assemble
// Favicon: the approved black YES mark on a white disc (an SVG wrapper, so the
// mark keeps its own pixels and stays legible on light and dark tab strips).
const favicon =
  'data:image/svg+xml,' +
  encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 64 64"><circle cx="32" cy="32" r="32" fill="#fff"/><image x="4" y="4" width="56" height="56" href="${brandUri('yes-logo-black.png')}"/></svg>`);
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
let html = readFileSync(join(SRC, 'index.html'), 'utf8');
html = html
  .replace('/*{{CSS}}*/', () => css)
  .replace('/*{{JS}}*/', () => js)
  .replace('{{NOSCRIPT}}', () => noscript)
  .replace('{{VERSION}}', () => pkg.version)
  .replace('{{FAVICON}}', () => favicon);

const leftovers = html.match(/\{\{[A-Z]+\}\}/g);
if (leftovers) fail('✖ Unreplaced template markers: ' + leftovers.join(', '));
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, html);
const kb = (b) => (b / 1024).toFixed(1);
const saved = MINIFY ? ` (comments and indentation stripped: −${kb(Buffer.byteLength(jsSource + cssSource) - Buffer.byteLength(js + css))} KB)` : ' (not minified)';
console.log(`✔ Release gate passed (${result.summary.postedCount} posted, ${result.summary.pendingCount} not in balance; ${result.checks.length} checks).`);
if (PDF_SAMPLE !== null) console.log(`✔ PDF writer: sample document is PDF 1.4${MINIFY ? ', byte-identical after minification' : ''}.`);
console.log(`✔ Built ${OUT.replace(ROOT + '/', '')} — ${kb(Buffer.byteLength(html))} KB, ${cssFiles.length} CSS + ${jsFiles.length} JS sources inlined${saved}.`);
