#!/usr/bin/env node
/*
 * Build the walkthrough app: src → public (or --out <dir>). SPEC section 2.
 *
 *   node build.mjs [--out dir] [--quiet]
 *
 * - Copies ../dist/yes-statement.html BYTE FOR BYTE to <out>/statement/index.html
 *   and fails if the copy's SHA-256 differs (runs `node ../build.mjs` first if
 *   the statement has not been built).
 * - Concatenates src/js/NN-*.js and src/css/NN-*.css in filename order into
 *   content-hashed app.<hash>.js / app.<hash>.css, with shared/features.json
 *   inlined as WT.features. The theme boot script (src/js/theme-boot.js) is
 *   written to assets/theme-boot.<hash>.js, since the CSP forbids inline script.
 * - Copies src/brand, src/shots, src/icons and the Inter variable font (latin
 *   subset) into <out>/assets/, plus favicon.ico, features.json and robots.txt.
 * - Is deterministic: the same inputs give byte-identical output.
 *
 * Programmatic use: import { build } from './build.mjs'; await build({ out }).
 */
import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, relative, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import vm from 'node:vm';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..');
const SRC = join(HERE, 'src');
const STATEMENT = join(REPO, 'dist', 'yes-statement.html');
const GENERATOR = 'infoslips-wt-build';
const VIEWS = ['start', 'tour', 'results', 'data', 'admin'];

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');
const short = (buf) => sha256(buf).slice(0, 10);

class BuildError extends Error {}

function listSorted(dir, re) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((n) => re.test(n))
    .sort();
}

function copyDir(from, to) {
  if (!existsSync(from)) return 0;
  let n = 0;
  for (const name of readdirSync(from).sort()) {
    if (name.startsWith('.')) continue;
    const src = join(from, name);
    const dst = join(to, name);
    const st = statSync(src);
    if (st.isDirectory()) n += copyDir(src, dst);
    else {
      mkdirSync(to, { recursive: true });
      copyFileSync(src, dst);
      n++;
    }
  }
  return n;
}

/** Only ever empty a directory that is empty or holds a previous build of this app. */
function prepareOut(out) {
  const forbidden = [HERE, REPO, SRC, resolve('/'), resolve(process.env.HOME || '/')];
  if (forbidden.includes(out)) throw new BuildError(`Refusing to build into ${out}. Choose a dedicated directory.`);
  if (existsSync(out)) {
    const entries = readdirSync(out);
    if (entries.length) {
      const index = join(out, 'index.html');
      const ours = existsSync(index) && readFileSync(index, 'utf8').includes(`content="${GENERATOR}"`);
      if (!ours) throw new BuildError(`Refusing to empty ${out}: it is not empty and does not hold a previous build of this app.`);
      for (const e of entries) rmSync(join(out, e), { recursive: true, force: true });
    }
  }
  mkdirSync(out, { recursive: true });
}

function ensureStatement(log) {
  if (existsSync(STATEMENT)) return;
  log('Statement not built yet: running node ../build.mjs');
  const r = spawnSync(process.execPath, ['build.mjs'], { cwd: REPO, stdio: 'inherit' });
  if (r.status !== 0 || !existsSync(STATEMENT)) throw new BuildError('Could not build ../dist/yes-statement.html');
}

function readFeatures() {
  const file = join(HERE, 'shared', 'features.json');
  const features = JSON.parse(readFileSync(file, 'utf8'));
  if (!Array.isArray(features) || !features.length) throw new BuildError('shared/features.json must be a non-empty array');
  const seen = new Set();
  const sections = new Set(['overview', 'transactions', 'understand', 'help', 'everywhere']);
  for (const f of features) {
    if (!f || typeof f.id !== 'string' || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(f.id)) throw new BuildError(`features.json: bad id ${JSON.stringify(f && f.id)}`);
    if (seen.has(f.id)) throw new BuildError(`features.json: duplicate id ${f.id}`);
    seen.add(f.id);
    if (!sections.has(f.section)) throw new BuildError(`features.json: ${f.id} has unknown section ${f.section}`);
    if (typeof f.title !== 'string' || !f.title.trim()) throw new BuildError(`features.json: ${f.id} has no title`);
  }
  return features;
}

/** Concatenate JS, checking syntax so a typo fails the build with the right file name. */
function bundleJs(features) {
  const dir = join(SRC, 'js');
  const files = listSorted(dir, /^\d{2}-[\w-]+\.js$/);
  const header =
    '/*! InfoSlips · YES statement review · app bundle generated by build.mjs — do not edit */\n' +
    "(function (WT) {\n  'use strict';\n  WT.features = " +
    JSON.stringify(features) +
    ';\n})(window.WT = window.WT || {});\n';
  const parts = [header];
  for (const f of files) {
    const code = readFileSync(join(dir, f), 'utf8');
    try {
      new vm.Script(code, { filename: `src/js/${f}` });
    } catch (e) {
      throw new BuildError(`Syntax error in src/js/${f}: ${e.message}\n${(e.stack || '').split('\n').slice(0, 3).join('\n')}`);
    }
    parts.push(`\n/* ---- ${f} ---- */\n${code.replace(/\s+$/, '')}\n;\n`);
  }
  return { code: parts.join(''), files };
}

function bundleCss() {
  const dir = join(SRC, 'css');
  const files = listSorted(dir, /^\d{2}-[\w-]+\.css$/);
  const parts = ['/*! InfoSlips · YES statement review · styles generated by build.mjs — do not edit */\n'];
  for (const f of files) parts.push(`\n/* ---- ${f} ---- */\n${readFileSync(join(dir, f), 'utf8').replace(/\s+$/, '')}\n`);
  return { code: parts.join(''), files };
}

function interFont() {
  const require = createRequire(import.meta.url);
  let pkgDir;
  try {
    pkgDir = dirname(require.resolve('@fontsource-variable/inter/package.json'));
  } catch {
    throw new BuildError('Missing @fontsource-variable/inter. Run npm install in walkthrough/.');
  }
  const woff2 = join(pkgDir, 'files', 'inter-latin-wght-normal.woff2');
  if (!existsSync(woff2)) throw new BuildError(`Inter latin woff2 not found at ${woff2}`);
  return { woff2, license: join(pkgDir, 'LICENSE') };
}

export async function build({ out = join(HERE, 'public'), quiet = false } = {}) {
  const log = quiet ? () => {} : (...a) => console.log(...a);
  const outDir = resolve(out);
  prepareOut(outDir);
  ensureStatement(log);

  // 1. The statement, byte for byte.
  const statementSrc = readFileSync(STATEMENT);
  const statementDst = join(outDir, 'statement', 'index.html');
  mkdirSync(dirname(statementDst), { recursive: true });
  writeFileSync(statementDst, statementSrc);
  const srcHash = sha256(statementSrc);
  const dstHash = sha256(readFileSync(statementDst));
  if (srcHash !== dstHash) throw new BuildError(`Statement copy differs from the source (${srcHash} vs ${dstHash})`);

  // 2. Bundles.
  const features = readFeatures();
  const js = bundleJs(features);
  const css = bundleCss();
  const jsName = `app.${short(js.code)}.js`;
  const cssName = `app.${short(css.code)}.css`;
  writeFileSync(join(outDir, jsName), js.code);
  writeFileSync(join(outDir, cssName), css.code);

  const bootSrc = join(SRC, 'js', 'theme-boot.js');
  if (!existsSync(bootSrc)) throw new BuildError('Missing src/js/theme-boot.js');
  const boot = readFileSync(bootSrc);
  const bootName = `assets/theme-boot.${short(boot)}.js`;
  mkdirSync(join(outDir, 'assets'), { recursive: true });
  writeFileSync(join(outDir, bootName), boot);

  // 3. Assets.
  const counts = {
    brand: copyDir(join(SRC, 'brand'), join(outDir, 'assets', 'brand')),
    shots: copyDir(join(SRC, 'shots'), join(outDir, 'assets', 'shots')),
    icons: copyDir(join(SRC, 'icons'), join(outDir, 'assets', 'icons')),
    // Images for the introduction email to YES, hosted here so email clients can load them.
    email: existsSync(join(SRC, 'email')) ? copyDir(join(SRC, 'email'), join(outDir, 'assets', 'email')) : 0
  };
  const font = interFont();
  mkdirSync(join(outDir, 'assets', 'fonts'), { recursive: true });
  copyFileSync(font.woff2, join(outDir, 'assets', 'fonts', 'inter-latin-wght-normal.woff2'));
  if (existsSync(font.license)) copyFileSync(font.license, join(outDir, 'assets', 'fonts', 'LICENSE-inter.txt'));
  if (existsSync(join(SRC, 'icons', 'favicon.ico'))) copyFileSync(join(SRC, 'icons', 'favicon.ico'), join(outDir, 'favicon.ico'));

  // 4. index.html.
  let html = readFileSync(join(SRC, 'index.html'), 'utf8');
  const fill = { '{{app.css}}': cssName, '{{app.js}}': jsName, '{{theme-boot.js}}': bootName, '{{generator}}': GENERATOR };
  for (const [k, v] of Object.entries(fill)) {
    if (!html.includes(k)) throw new BuildError(`src/index.html is missing the ${k} placeholder`);
    html = html.split(k).join(v);
  }
  const left = html.match(/\{\{[^}]*\}\}/);
  if (left) throw new BuildError(`src/index.html has an unknown placeholder ${left[0]}`);
  for (const v of VIEWS) if (!html.includes(`id="view-${v}"`)) throw new BuildError(`src/index.html has no <section id="view-${v}">`);
  writeFileSync(join(outDir, 'index.html'), html);

  // 5. Data files.
  writeFileSync(join(outDir, 'features.json'), JSON.stringify(features, null, 2) + '\n');
  writeFileSync(join(outDir, 'robots.txt'), 'User-agent: *\nDisallow: /\n');

  const kb = (n) => (n / 1024).toFixed(1) + ' KB';
  const shown = relative(process.cwd(), outDir);
  log(`Built ${!shown ? '.' : shown.startsWith('..') ? outDir : shown}`);
  log(`  ${jsName} (${kb(js.code.length)}, ${js.files.length} modules: ${js.files.join(', ')})`);
  log(`  ${cssName} (${kb(css.code.length)}, ${css.files.length} files)`);
  log(`  statement/index.html (${kb(statementSrc.length)}, sha256 ${srcHash.slice(0, 16)}… identical to dist)`);
  log(`  assets: ${counts.brand} brand, ${counts.shots} shots, ${counts.icons} icons, ${counts.email} email, Inter woff2`);
  return { out: outDir, js: jsName, css: cssName, boot: bootName, statementSha256: srcHash, modules: js.files, styles: css.files };
}

function argValue(name) {
  const i = process.argv.indexOf(name);
  if (i !== -1) return process.argv[i + 1];
  const eq = process.argv.find((a) => a.startsWith(name + '='));
  return eq ? eq.slice(name.length + 1) : null;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const out = argValue('--out');
  build({ out: out ? resolve(out) : join(HERE, 'public'), quiet: process.argv.includes('--quiet') }).catch((e) => {
    console.error('Build failed: ' + (e instanceof BuildError ? e.message : e.stack || e));
    process.exit(1);
  });
}

